CREATE TYPE "CollectionRole" AS ENUM ('OWNER','EDITOR','VIEWER');
CREATE TYPE "GameCopyFormat" AS ENUM ('PHYSICAL','DIGITAL');
CREATE TYPE "GamePartType" AS ENUM ('DISC','CARTRIDGE','CASE','BOX','MANUAL','INSERT','COVER_ART','STEELBOOK','AMIIBO','OTHER');
CREATE TYPE "ConditionGrade" AS ENUM ('NEW','LIKE_NEW','VERY_GOOD','GOOD','ACCEPTABLE','POOR','MISSING');
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"name" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Collection" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Collection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CollectionMember" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"collectionId" TEXT NOT NULL,"role" "CollectionRole" NOT NULL DEFAULT 'VIEWER',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CollectionMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Platform" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"maker" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Platform_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Game" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"releaseYear" INTEGER,"coverUrl" TEXT,"platformId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Game_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GameCopy" ("id" TEXT NOT NULL,"collectionId" TEXT NOT NULL,"gameId" TEXT NOT NULL,"format" "GameCopyFormat" NOT NULL DEFAULT 'PHYSICAL',"region" TEXT,"edition" TEXT,"purchaseDate" TIMESTAMP(3),"purchasePrice" DECIMAL(10,2),"estimatedValue" DECIMAL(10,2),"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "GameCopy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GamePart" ("id" TEXT NOT NULL,"copyId" TEXT NOT NULL,"type" "GamePartType" NOT NULL,"condition" "ConditionGrade" NOT NULL DEFAULT 'GOOD',"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GamePart_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "CollectionMember_userId_collectionId_key" ON "CollectionMember"("userId","collectionId");
CREATE UNIQUE INDEX "Platform_name_key" ON "Platform"("name");
CREATE INDEX "Game_title_idx" ON "Game"("title");
ALTER TABLE "CollectionMember" ADD CONSTRAINT "CollectionMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CollectionMember" ADD CONSTRAINT "CollectionMember_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "Collection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Game" ADD CONSTRAINT "Game_platformId_fkey" FOREIGN KEY ("platformId") REFERENCES "Platform"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "GameCopy" ADD CONSTRAINT "GameCopy_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "Collection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GameCopy" ADD CONSTRAINT "GameCopy_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GamePart" ADD CONSTRAINT "GamePart_copyId_fkey" FOREIGN KEY ("copyId") REFERENCES "GameCopy"("id") ON DELETE CASCADE ON UPDATE CASCADE;
