ALTER TABLE "AppSetting"
ADD COLUMN "smtpHost" TEXT,
ADD COLUMN "smtpPort" INTEGER NOT NULL DEFAULT 587,
ADD COLUMN "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "smtpUser" TEXT,
ADD COLUMN "smtpPass" TEXT,
ADD COLUMN "smtpFrom" TEXT;
