ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "assetLabelWidth" DOUBLE PRECISION NOT NULL DEFAULT 2.25;
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "assetLabelHeight" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
