ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "appName" TEXT NOT NULL DEFAULT 'VGC Shelf';
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "pageTitle" TEXT NOT NULL DEFAULT 'VGC Shelf';
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "appIconUrl" TEXT;
